version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - gin_gorm_api_db_data:/var/lib/mysql

  go:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/app

volumes:
  gin_gorm_api_db_data:
